### ISSUE TITLE
Show balance due extension not working for civicrm 5.37.2-0 (on Drupal)

### ISSUE THREAD

**Issue by guitto13** [JMAConsulting/biz.jmaconsulting.showbalancedue#3]
Testing civicrm 5.37.2-0 on drupal i cannot make "Show balance due" extension working. Below what i get:
![image](https://user-images.githubusercontent.com/87032216/124637103-995fa480-de89-11eb-8938-721aa16911a4.png)

Also this exception is thrown:
```
User deprecated function: Deprecated function CRM_Core_BAO_FinancialTrxn::getPartialPaymentWithType, use CRM_Contribute_BAO_Contribution::getContributionBalance. in CRM_Core_Error::deprecatedWarning() (line 1053 of /bitnami/drupal/modules/contrib/civicrm/CRM/Core/Error.php).
User deprecated function: Deprecated function CRM_Core_BAO_FinancialTrxn::getPartialPaymentWithType, use CRM_Contribute_BAO_Contribution::getContributionBalance. in CRM_Core_Error::deprecatedWarning() (line 1053 of /bitnami/drupal/modules/contrib/civicrm/CRM/Core/Error.php). ```

```
Could you please have a look?

Kind regards
Antonio

**Comment by monishdeb** [comment]
@guitto13 thanks for your report but I am not able to replicate the issue in my local. I think this issue get resolved last year and this is the patch https://github.com/JMAConsulting/biz.jmaconsulting.showbalancedue/pull/1 . Can you please try the latest code of biz.jmaconsulting.showbalancedue ?

**Comment by monishdeb** [comment]
On the other hand, I am going to publish a new release v2.0 against the latest stable CiviCRM v 5.38.1.

**Comment by guitto13** [comment]
Thanks@monishdeb! Works like a charm.
